config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root to: "home#index"

  resources :categories, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
  end

  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :recipe
  belongs_to :category

#   - A bookmark must be linked to a recipe and a category, and the [recipe, category] pairings should be unique.
# - The comment of a bookmark cannot be shorter than 6 characters.
validates :recipe_id, uniqueness: { scope: :category_id }
validates :comment, length: { minimum: 6, too_short: "must have at least 6 characters" }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :recipes, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    has_many :bookmarks

    validates :name, presence: true, uniqueness: true
    validates :description, presence: true
    validates :rating, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @category = Category.find(params[:category_id])
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @category = Category.find(params[:category_id])
    @bookmark.category = @category
    if @bookmark.save
      redirect_to category_path(@category)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to category_path(@bookmark.category)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :recipe_id)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/bookmarks/new.html.erb
<div class="navbar">
  <%= image_tag 'logo.png' %>
  <div>
    <%= link_to 'Home', root_path %>
    <%= link_to "new category", new_category_path %>
  </div>
</div>

<div class="form-new mt-5">
  <h1>Add a Recipe</h1>
  <%= simple_form_for [@category, @bookmark] do |f| %>
    <%= f.association :recipe %>
    <%= f.input :comment, placeholder: "Comment here..." %>
    <%= f.submit class: "btn btn-info"%>
  <% end %>
</div>

app/views/categories/index.html.erb
<div class="navbar">
  <%= image_tag 'logo.png' %>
  <div>
    <%= link_to 'Home', root_path %>
    <%= link_to "new category", new_category_path %>
  </div>
</div>

<div class="banner" style="background-image: url('<%= image_path "banner.jpg" %>')">
  <div>
    <h1>Cookbook</h1>
    <h3>Save Your Favourite Recipes</h3>
  </div>
</div>

<div class="container">

  <div class="info-top">
    <h3>List of Categories</h3>
    <%= link_to 'New Category', new_category_path, class: "btn btn-warning" %>
  </div>

  <div class="cards">
    <% @categories.each do |category| %>

      <%= link_to category_path(category) do %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= image_path "category.jpg" %>')">
          <h2><%= category.name %></h2>
        </div>
     <% end %>

    <% end %>
  </div>
</div>

app/views/categories/new.html.erb
<div class="navbar">
  <%= image_tag 'logo.png' %>
  <div>
    <%= link_to 'Home', root_path %>
    <%= link_to "new category", new_category_path %>
  </div>
</div>


<div class="form-new mt-5">
  <h1>Create a New Category</h1>
  <%= simple_form_for @category do |f| %>
    <%= f.input :name, label: false, placeholder: "Category name..." %>
    <%= f.submit class: "btn btn-info" %>
  <% end %>
</div>

app/views/categories/show.html.erb
<div class="navbar">
  <%= image_tag 'logo.png' %>
  <div>
    <%= link_to 'Home', root_path %>
    <%= link_to "new category", new_category_path %>
  </div>
</div>

<div class="banner" style="background-image: url('<%= image_path "category.jpg" %>')">
  <div>
    <h1><%= @category.name %></h1>
  </div>
</div>

<div class="container">
  <div class="info-top">
      <h3>Recipes</h3>
      <%= link_to 'Add a Recipe', new_category_bookmark_path(@category), class: "btn btn-warning" %>
  </div>

  <div class="cards">
      <% @category.bookmarks.each do |bookmark| %>
        <div class="card-recipe">

          <%= link_to bookmark_path(bookmark),
                      data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
                      class: 'btn-delete' do %>

            <i class="fa-solid fa-trash"></i>
          <% end %>

          <img src="<%= bookmark.recipe.image_url %>" alt="recipe image">

          <div class="card-recipe-description">
            <h2><%= bookmark.recipe.name %></h2>
            <p><%= bookmark.recipe.description.truncate(200) %></p>
          </div>

          <div class="card-recipe-info">
            <div>
              <i class="fa-solid fa-quote-left"></i><%= bookmark.comment %>
            </div>

            <div>
              <%= bookmark.recipe.rating %>
            </div>

          </div>>

        </div>
      <% end %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsRailsCookbook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>